In [4]:
import pandas as pd
import os
import glob

In [30]:
#Read in all CSVs to a dataframe using glob
# This code was inspired by the stackoverflow thread:    https://stackoverflow.com/questions/20906474/import-multiple-csv-files-into-pandas-and-concatenate-into-one-dataframe

apd_raw_df = pd.concat(map(pd.read_csv, glob.glob('Data_files/APD_data_2018_to_2020/*.csv')))

In [31]:
#review raw data
apd_raw_df

,UC2_Literal,Report Number,Report Date,Location,Beat,Neigborhood,NPU,Lat,Long,Unnamed: 9,Unnamed: 10
0,ROBBERY-PEDESTRIAN,180312381,01/31/2018,1695 MARIETTA BLVD NW,203,Hills Park,D,33.8009,-84.4345,NaN,NaN
1,ROBBERY-PEDESTRIAN,180310247,01/31/2018,2350 CHESHIRE BRIDGE RD NE,212,Lindridge/Martin Manor,F,33.8195,-84.352,NaN,NaN
2,ROBBERY-PEDESTRIAN,180310249,01/31/2018,1305 OAKLAND DR SW @OAKLAND CITY PARK,403,Oakland City,S,33.719,-84.4289,NaN,NaN
3,ROBBERY-PEDESTRIAN,180312606,01/31/2018,520 FLAT SHOALS AVE SE,612,East Atlanta,W,33.7395,-84.3446,NaN,NaN
4,AGG ASSAULT,180310884,01/31/2018,515 FULTON ST SW,303,Mechanicsville,V,33.741,-84.4045,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1652,AUTO THEFT,201530392,6/1/2020,632 ELOISE ST SE,605,Grant Park,W,33.73624,-84.36261,NaN,NaN
1653,LARCENY,201530422,6/1/2020,2135 BRIAR GLEN LN SW,412,Briar Glen,P,33.69523,-84.5026,NaN,NaN
1654,LARCENY,201530516,6/1/2020,145 EDGEWOOD AVE SE,510,Downtown,M,33.75421,-84.38294,NaN,NaN
1655,AUTO THEFT,201530525,6/1/2020,433 HIGHLAND AVE NE,604,Old Fourth Ward,M,33.76101,-84.37345,NaN,NaN
1656,BURGLARY,201530609,6/1/2020,78 BROAD ST NW,508,Downtown,M,33.7561,-84.38902,NaN,NaN

In [35]:
#create new dataframe with desired columns
apd_df = apd_df_raw[['UC2_Literal', 'Report Number', 'Report Date', 'Location', 'Beat', 'Neigborhood', 'NPU', 'Lat', 'Long']].copy()

In [37]:
#rename the UC2_Literal column
apd_df = apd_df.rename(columns={'UC2_Literal': 'Crime Type'})
apd_df

,Crime Type,Report Number,Report Date,Location,Beat,Neigborhood,NPU,Lat,Long
0,ROBBERY-PEDESTRIAN,180312381,01/31/2018,1695 MARIETTA BLVD NW,203,Hills Park,D,33.8009,-84.4345
1,ROBBERY-PEDESTRIAN,180310247,01/31/2018,2350 CHESHIRE BRIDGE RD NE,212,Lindridge/Martin Manor,F,33.8195,-84.352
2,ROBBERY-PEDESTRIAN,180310249,01/31/2018,1305 OAKLAND DR SW @OAKLAND CITY PARK,403,Oakland City,S,33.719,-84.4289
3,ROBBERY-PEDESTRIAN,180312606,01/31/2018,520 FLAT SHOALS AVE SE,612,East Atlanta,W,33.7395,-84.3446
4,AGG ASSAULT,180310884,01/31/2018,515 FULTON ST SW,303,Mechanicsville,V,33.741,-84.4045
...,...,...,...,...,...,...,...,...,...
1652,AUTO THEFT,201530392,6/1/2020,632 ELOISE ST SE,605,Grant Park,W,33.73624,-84.36261
1653,LARCENY,201530422,6/1/2020,2135 BRIAR GLEN LN SW,412,Briar Glen,P,33.69523,-84.5026
1654,LARCENY,201530516,6/1/2020,145 EDGEWOOD AVE SE,510,Downtown,M,33.75421,-84.38294
1655,AUTO THEFT,201530525,6/1/2020,433 HIGHLAND AVE NE,604,Old Fourth Ward,M,33.76101,-84.37345
1656,BURGLARY,201530609,6/1/2020,78 BROAD ST NW,508,Downtown,M,33.7561,-84.38902

In [39]:
#save merged data to csv
apd_df.to_csv('merged_2018_to_2020.csv',index=False)